{% set version = "2.1.0" %}
{% set name = "iris-sample-data" %}
{% set sha256 = "370066e5e43e8aa0c3ae9d7ef727fc1e28f11a5f965bc7864846013599df8135" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/SciTools/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - iris_sample_data

about:
    home: https://github.com/SciTools/{{ name }}
    license: Open Government
    summary: 'Iris sample data.'

extra:
    recipe-maintainers:
        - ocefpaf
        - bjlittle
        - dkillick
