travis:
  secure:
    BINSTAR_TOKEN: cxtKKUPCFUlaIf1pgkZwYmEYWcdkxhCYd0BLYit/BTOtR2d8HgGJBa/jmdD8oQZzTka02XTHdmImbiv3G07cy2cA5HGKYbFTEADTiup7QuIx4ugaeEH0KE5LcBZDHBm+5hP6+y01ZERFbzjrrYTw91g3m4oKpW+lpvaj1nbMrrK7voTlR59LlwR0RMBXqE1iumQBx3fd7A42WkoUxm2YubGkPUARtbA1WGuKIloakKx+LlICEK4roBUj2ssEyAF8Dlg8BTQQWDzhyk3YCEkaKz6UNEbx+qgSGQkXb1jGp5XGfg4nqq4XPoGzJpyluNGXZjhqGQgW5FaW5TkSjpy3RxlgKHp2PgXiQVqzc6jJKxkSw/L4gufBqMdcbJavbqF3F3SPBnXpUdnq2Qg+5iPXbACLvVXqSQ4+mTQIcbGpYxI7ELWaWXFmHvYPauF7nelPU8+p9jbQFDkXvr90GJO9RFjGXkKxxZW8+Kx1Kl/vbJodFA2CsrQ5RM+wY11Sr4GBpwJhbyM8CEdLZUecIpKpkyDrohBzW2KerGq8GwxtJrPmlBaAL9i8hEReOB9fU3/XGxTIISAnOVuuyu6biVCnz+QqOGuEq0sX8efW606xHiJHhCKfDW/P0phsmsS3aU2WjOMH3PSeP2xaNMJPutVOttSg5pUSrP9pEMOO0mOmQ1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
